/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import io.javalin.Javalin;
import org.example.controllers.Controller;



public class App {
    public static void main(String[] args) {
         Javalin app = Javalin.create(config -> {
            config.staticFiles.add("/public");
        }).start(7000);
        
        app.get("/", Controller::helloWorld);  // Replace this with your own route handler
    }
}
